+dj/kill.m: update (add connection, order_by support) - fix #229
datajoint/datajoint-matlab pull request #248
Opened 2020-06-26 22:20 UTC by ixcat

having issues with mym currently - draft until validation

2020-07-06 19:03 UTC, ixcat commented
todo:
- support both single string and cell array of strings.

2020-07-31 15:58 UTC, ixcat commented
Thanks @dimitri-yatsenko - I believe all comments are addressed in last commit.

2020-08-07 23:21 UTC, ixcat commented
see also: https://github.com/datajoint/datajoint-matlab/issues/229

2020-08-08 01:02 UTC, ixcat commented
^ should include docs-parts per https://github.com/datajoint/datajoint-docs/issues/237

2020-10-09 18:47 UTC, guzman-raphael requested changes
Can you update the docs to use `matlab` highlighting?

2020-10-09 18:47 UTC, guzman-raphael commented on docs-parts/computation/06-distributed-computing_kill_order_by.rst
> +.. code-block:: text
```suggestion
.. code-block:: matlab
```

2020-10-09 18:47 UTC, guzman-raphael commented on docs-parts/computation/06-distributed-computing_kill_order_by.rst
> +    >> dj.kill('', dj.conn, 'host desc');
```suggestion
    dj.kill('', dj.conn, 'host desc');
```

2020-10-09 23:27 UTC, ixcat commented on docs-parts/computation/06-distributed-computing_kill_order_by.rst
> +    >> dj.kill('', dj.conn, 'host desc');
adjusted in e5c655c

2020-10-09 23:28 UTC, ixcat commented on docs-parts/computation/06-distributed-computing_kill_order_by.rst
> +.. code-block:: text
adjusted in e5c655c

2020-10-09 23:28 UTC, merged