connection/jobs table update: track server connid, add user/id to jobs table
datajoint/datajoint-matlab pull request #308
Opened 2020-10-30 21:14 UTC by ixcat

to fix issue #87, #275 (add user/server connection to jobs table).

ideally, connection ID would be directly available via MyM; for the moment,
hack in a query to retrieve connection ID on connection and use this for
jobs table logging.

supersedes: https://github.com/datajoint/datajoint-matlab/pull/276

addresses: https://github.com/datajoint/datajoint-matlab/pull/276#discussion_r506583746:
- [X] r.e. recurse: adjust to direct mym calls
- [X] r.e. indexing: feature too new, save ref and index that

status/remaining:
- [X] base functionality
- [ ] unit test

2020-10-30 21:20 UTC, guzman-raphael commented
@ixcat You will need to target a `stage-external-storage*` like branch first in order for the tests to work properly. Can you create another branch, e.g. `stage-external-storage2` since the current stage is already being used fro #303?

2020-10-30 21:29 UTC, ixcat commented
ah right, got confused. will readjust.

2020-11-08 00:04 UTC, dimitri-yatsenko approved these changes

2020-11-12 18:28 UTC, guzman-raphael requested changes
Looking good! Thanks for getting this test case together; I like it :smile:.
Only a few minor nits on comment docs. Not necessary to implement exactly my suggestion but just looking to maintain some consistency.

2020-11-12 18:28 UTC, guzman-raphael commented on +dj/+internal/AutoPopulate.m
> +            %   connection_id=0   : bigint unsigned       # system process id
```suggestion
            %   connection_id=0   : bigint unsigned       # database connection id
```

2020-11-12 18:28 UTC, guzman-raphael commented on +dj/+internal/AutoPopulate.m
> +            fprintf(f, 'connection_id=0    : bigint unsigned          # connection_id()\n');
```suggestion
            fprintf(f, 'connection_id=0    : bigint unsigned          # database connection id\n');
```

2020-11-12 18:28 UTC, guzman-raphael commented on +dj/Connection.m
> +        serverId     % server connection ID
```suggestion
        serverId     % database connection id
```

2020-11-12 18:28 UTC, guzman-raphael commented on +dj/conn.m
> +    fprintf('server connection id: %d\n', connObj.serverId);
```suggestion
    fprintf('database connection id: %d\n', connObj.serverId);    
```

2020-11-25 17:09 UTC, ixcat commented on +dj/+internal/AutoPopulate.m
> +            %   connection_id=0   : bigint unsigned       # system process id
good catch(es). updated / resolving all.

2020-11-27 15:48 UTC, guzman-raphael approved these changes

2020-11-27 15:51 UTC, merged